name: 'Setup PKS Devcontainer Runner'
description: 'Prepare a PKS self-hosted devcontainer runner: trust .NET dev certs, set environment variables.'

inputs:
  trust-dev-certs:
    description: 'Generate and trust .NET HTTPS development certificates'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Trust .NET dev certs
      if: inputs.trust-dev-certs == 'true'
      shell: bash
      run: |
        # The devcontainer already has:
        #   - libnss3-tools (provides certutil for NSS trust)
        #   - SSL_CERT_DIR pointing to ~/.aspnet/dev-certs/trust
        #
        # We just need to run --trust which:
        #   1. Generates the dev cert PFX in ~/.dotnet/corefx/cryptography/x509stores/my/
        #   2. Exports PEM + hash symlink to ~/.aspnet/dev-certs/trust/
        #   3. Adds to NSS database via certutil

        TRUST_DIR="$HOME/.aspnet/dev-certs/trust"
        if [ -d "$TRUST_DIR" ] && [ -n "$(ls -A "$TRUST_DIR" 2>/dev/null)" ]; then
          echo "Dev certs already trusted (reused container), skipping generation"
        else
          echo "Generating and trusting dev certs..."
          # || true: workaround for .NET SDK 10.0.103 bug — EventSource ID mismatch
          # causes exit code 4 even though the cert IS successfully trusted.
          # See: https://github.com/dotnet/sdk/issues — WslWindowsTrustSucceeded ID 115 vs 113
          dotnet dev-certs https --trust || true
          echo "Dev certs generated and trusted"
        fi

        # Ensure SSL_CERT_DIR includes the trust directory (may already be set by devcontainer.json)
        if [[ "${SSL_CERT_DIR:-}" != *"$TRUST_DIR"* ]]; then
          echo "SSL_CERT_DIR=${TRUST_DIR}:/usr/lib/ssl/certs" >> "$GITHUB_ENV"
        fi

        # Set NODE_EXTRA_CA_CERTS for Node.js tools
        echo "NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt" >> "$GITHUB_ENV"

    - name: Set PKS runner environment
      shell: bash
      run: |
        echo "ASPNETCORE_ENVIRONMENT=Development" >> "$GITHUB_ENV"
        echo "DOTNET_RUNNING_IN_CONTAINER=true" >> "$GITHUB_ENV"

    - name: Verify dev certs
      if: inputs.trust-dev-certs == 'true'
      shell: bash
      run: |
        # || true: same .NET SDK 10.0.103 EventSource bug applies to --check --trust
        dotnet dev-certs https --check --trust 2>&1 || true
        echo "Dev certs configured for PKS runner"
