#!/bin/bash
# Post-build tasks hook for {{ProjectName}}
# Generated by PKS CLI

echo "✅ Post-build tasks for {{ProjectName}}"

# Read JSON input
json_input=$(cat)
command=$(echo "$json_input" | jq -r '.command // empty')

# Check build output
echo "Checking build output..."

case "{{Template}}" in
    "api"|"web"|"console")
        if [ -d "bin" ]; then
            echo "✅ Build output directory found"
            
            # Count output files
            output_count=$(find bin -name "*.dll" 2>/dev/null | wc -l)
            echo "📦 Found $output_count output assemblies"
        else
            echo "⚠️  Build output directory not found"
        fi
        ;;
    *)
        echo "✅ Generic post-build validation passed"
        ;;
esac

# Optional: Generate build report
build_time=$(date)
echo "📊 Build completed at: $build_time"

# Optional: Run post-build tests
if [ -f "tests" ] && command -v dotnet &> /dev/null; then
    echo "🧪 Running post-build tests..."
    # Uncomment to enable automatic test execution
    # dotnet test --no-build --verbosity minimal
fi

echo "🎉 Post-build tasks completed for {{ProjectName}}"
exit 0