#!/bin/bash
# Post-deployment verification hook for {{ProjectName}}
# Generated by PKS CLI

echo "🎉 Post-deployment verification for {{ProjectName}}"

# Read JSON input
json_input=$(cat)
command=$(echo "$json_input" | jq -r '.command // empty')
environment=$(echo "$json_input" | jq -r '.environment // "production"')

echo "🎯 Verifying deployment in: $environment"

# Environment-specific verifications
case "$environment" in
    "production"|"prod")
        echo "🔍 Running production deployment verification..."
        
        # Health check (example)
        if command -v curl &> /dev/null; then
            echo "🏥 Performing health check..."
            # Uncomment and customize for your service
            # if curl -f -s http://localhost:5000/health > /dev/null; then
            #     echo "✅ Health check passed"
            # else
            #     echo "❌ Health check failed"
            #     exit 1
            # fi
        fi
        ;;
    "staging"|"stage")
        echo "🔧 Running staging deployment verification..."
        ;;
    "development"|"dev")
        echo "🛠️  Running development deployment verification..."
        ;;
    *)
        echo "⚠️  Unknown environment: $environment"
        ;;
esac

# Verify deployment artifacts
echo "📦 Verifying deployment artifacts..."

# Check if service is running (generic check)
echo "🔍 Checking service status..."

# Log deployment completion
deployment_time=$(date)
echo "📊 Deployment completed at: $deployment_time"

# Optional: Send notifications
echo "📢 Deployment notifications..."
# Add notification logic here (Slack, email, etc.)

# Optional: Run smoke tests
echo "🧪 Running post-deployment smoke tests..."
# Add smoke test logic here

echo "🎊 Post-deployment verification completed for {{ProjectName}}"
echo "🌟 {{ProjectName}} deployment successful in $environment!"

exit 0