#!/bin/bash
# Pre-build validation hook for {{ProjectName}}
# Generated by PKS CLI

echo "🔨 Pre-build validation for {{ProjectName}}"

# Read JSON input
json_input=$(cat)
command=$(echo "$json_input" | jq -r '.command // empty')

# Validate build prerequisites
echo "Checking build prerequisites..."

# Check for required tools based on template
case "{{Template}}" in
    "api"|"web"|"console")
        if ! command -v dotnet &> /dev/null; then
            echo "❌ .NET CLI not found"
            exit 1
        fi
        echo "✅ .NET CLI found"
        ;;
    *)
        echo "✅ Generic build validation passed"
        ;;
esac

# Validate project files exist
if [ -f "{{ProjectName}}.csproj" ] || [ -f "{{ProjectName}}.sln" ]; then
    echo "✅ Project files found"
else
    echo "⚠️  Project files not found in current directory"
fi

# Check for uncommitted changes (optional warning)
if git status --porcelain 2>/dev/null | grep -q .; then
    echo "⚠️  Uncommitted changes detected"
fi

echo "✅ Pre-build validation completed for {{ProjectName}}"
exit 0