#!/bin/bash
# PKS CLI Smart Hook Dispatcher
# Generated by PKS CLI for {{ProjectName}}
# Implements intelligent command routing to avoid performance penalties

# Read JSON input from stdin
json_input=$(cat)

# Extract command from JSON input
command=$(echo "$json_input" | jq -r '.command // empty')

# Exit early if no command
if [ -z "$command" ]; then
    exit 0
fi

echo "🎯 Smart dispatcher analyzing command for {{ProjectName}}..."

# Smart routing based on command patterns
if echo "$command" | grep -q "build"; then
    echo "🔨 Running build validation for {{ProjectName}}..."
    ./hooks/pre-build.sh <<< "$json_input"
    exit $?
fi

if echo "$command" | grep -q "deploy"; then
    echo "🚀 Running deployment validation for {{ProjectName}}..."
    ./hooks/pre-deploy.sh <<< "$json_input"
    exit $?
fi

if echo "$command" | grep -q "test"; then
    echo "🧪 Running test validation for {{ProjectName}}..."
    ./hooks/pre-test.sh <<< "$json_input"
    exit $?
fi

if echo "$command" | grep -q "docker"; then
    echo "🐳 Running Docker validation for {{ProjectName}}..."
    ./hooks/docker-validation.sh <<< "$json_input"
    exit $?
fi

# Skip simple commands to avoid performance penalties
if echo "$command" | grep -E "^(ls|pwd|cd|echo|cat|grep)"; then
    exit 0
fi

# Default: Continue with general validation
echo "✓ Command passed smart dispatcher validation for {{ProjectName}}"
exit 0