name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test - Core Stable Tests Only (CI Ready)
      run: |
        cd tests
        dotnet test --no-build --settings .runsettings \
          --filter "Category=Core&Reliability!=Unstable" \
          --logger "console;verbosity=normal" \
          --logger "trx;LogFileName=core-tests.trx" \
          --logger "html;LogFileName=core-tests.html" \
          --results-directory ../test-artifacts/results \
          --collect "XPlat Code Coverage"
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false