using System.Text;
using PKS.Infrastructure.Services.Security;

namespace PKS.Infrastructure.Services.Runner;

/// <summary>
/// Writes the throwaway <c>GIT_ASKPASS</c> script the runner points git at.
///
/// The script embeds the stored GitHub token as a literal, so composing it is credential handling and
/// belongs here rather than in the command that calls it: the command supplies the token as a
/// <see cref="SecretValue"/> and gets back a path, which is exactly the split the quarantine asks for.
/// </summary>
public static class GitAskpassScript
{
    /// <summary>
    /// Writes a 0700 dispatch script to the temp directory and returns its path.
    ///
    /// Dispatch is on the prompt text itself — git asks <c>Password for 'https://host/…'</c>, so the
    /// URL appears verbatim in <c>$1</c>:
    /// <list type="bullet">
    ///   <item>dev.azure.com / visualstudio.com → shells back into <c>pks git askpass</c>, because the
    ///   ADO credential is short-lived and has to be refreshed per request.</item>
    ///   <item>anything else → answers with the static GitHub token.</item>
    /// </list>
    /// Without a token the password branch exits non-zero, so git fails fast under
    /// <c>GIT_TERMINAL_PROMPT=0</c> instead of hanging on a prompt nobody can answer.
    /// </summary>
    /// <param name="gitHubToken">The stored GitHub token, or <see cref="SecretValue.None"/>.</param>
    /// <param name="pksBinaryPath">Path to the running pks-cli executable, for the ADO delegation.</param>
    public static async Task<string> WriteAsync(
        SecretValue gitHubToken, string pksBinaryPath, CancellationToken cancellationToken = default)
    {
        var scriptPath = Path.Combine(Path.GetTempPath(), $"git-askpass-{Guid.NewGuid():N}.sh");

        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/sh");
        sb.AppendLine("# Auto-generated by pks-cli agentics runner. Multi-host credential dispatch.");
        sb.AppendLine("prompt=\"$1\"");
        sb.AppendLine("case \"$prompt\" in");
        sb.AppendLine("  *dev.azure.com*|*visualstudio.com*)");
        sb.AppendLine($"    exec \"{pksBinaryPath}\" git askpass \"$prompt\"");
        sb.AppendLine("    ;;");
        sb.AppendLine("esac");
        sb.AppendLine("case \"$prompt\" in");
        sb.AppendLine("  *Username*) echo \"x-access-token\" ;;");
        if (gitHubToken.HasValue)
            sb.AppendLine($"  *Password*) echo \"{gitHubToken.Reveal()}\" ;;");
        else
            sb.AppendLine("  *Password*) exit 1 ;;");
        sb.AppendLine("  *) exit 1 ;;");
        sb.AppendLine("esac");

        await File.WriteAllTextAsync(scriptPath, sb.ToString(), cancellationToken);

        if (OperatingSystem.IsLinux() || OperatingSystem.IsMacOS())
        {
            // Owner-only: the file holds a live token, and the temp directory is world-readable.
            File.SetUnixFileMode(scriptPath,
                UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute);
        }

        return scriptPath;
    }
}
