using System.ComponentModel;
using Spectre.Console;
using Spectre.Console.Cli;
using PKS.Infrastructure.Services.Writing;

namespace PKS.Commands.Writing;

public class WritingProfileIngestSettings : WritingSettings
{
    [CommandArgument(0, "<bundle>")]
    [Description("Path to the bundle file. May be raw JSON or a Markdown reply containing a ```json block.")]
    public string Bundle { get; set; } = "";

    [CommandOption("--force")]
    [Description("Overwrite existing profile.md and reference samples. Defaults skip if present (except untouched template).")]
    public bool Force { get; set; }
}

public class WritingProfileIngestCommand : AsyncCommand<WritingProfileIngestSettings>
{
    private readonly IWritingPathResolver _paths;
    private readonly IWritingProfileStore _store;

    public WritingProfileIngestCommand(IWritingPathResolver paths, IWritingProfileStore store)
    {
        _paths = paths;
        _store = store;
    }

    public override async Task<int> ExecuteAsync(CommandContext context, WritingProfileIngestSettings settings)
    {
        if (string.IsNullOrWhiteSpace(settings.Bundle))
        {
            AnsiConsole.MarkupLine("[red]error:[/] bundle path required.");
            return 1;
        }

        var path = System.IO.Path.GetFullPath(ExpandHome(settings.Bundle));
        if (!System.IO.File.Exists(path))
        {
            AnsiConsole.MarkupLine($"[red]error:[/] file not found: [cyan]{path}[/]");
            return 1;
        }

        var text = await System.IO.File.ReadAllTextAsync(path);
        var (bundle, err) = WritingBundleIngestor.Parse(text);
        if (bundle is null)
        {
            AnsiConsole.MarkupLine($"[red]error:[/] {Markup.Escape(err ?? "unknown parse error")}");
            return 1;
        }

        AnsiConsole.WriteLine();
        AnsiConsole.Write(new Rule($"[bold magenta]pks writing profile ingest[/] [grey](v{bundle.Version})[/]")
            .RuleStyle("magenta dim"));
        AnsiConsole.WriteLine();
        if (!string.IsNullOrWhiteSpace(bundle.GeneratedBy))
            AnsiConsole.MarkupLine($"  Generated by: [cyan]{Markup.Escape(bundle.GeneratedBy)}[/]");
        if (bundle.GeneratedAt is { } at)
            AnsiConsole.MarkupLine($"  Generated at: [cyan]{at:u}[/]");
        AnsiConsole.WriteLine();

        var result = await WritingBundleIngestor.ApplyAsync(bundle, _paths, _store, settings.Force);

        // Summary table.
        var t = new Table().Border(TableBorder.Minimal).HideHeaders();
        t.AddColumn(""); t.AddColumn(new TableColumn("").RightAligned());

        t.AddRow("Profile",
            result.ProfileWritten ? "[green]written[/]" :
            result.ProfileSkipped ? "[yellow]skipped (existed; re-run with --force)[/]" :
            "[grey]not in bundle[/]");

        t.AddRow("Anglicisms added", $"[green]{result.AnglicismsAdded}[/]");
        t.AddRow("Allowlist added",  $"[green]{result.AllowlistAdded}[/]");

        if (result.ReferencesAdded.Count > 0 || result.ReferencesSkipped.Count > 0)
        {
            var channels = result.ReferencesAdded.Keys.Concat(result.ReferencesSkipped.Keys).Distinct().OrderBy(k => k);
            foreach (var ch in channels)
            {
                var added = result.ReferencesAdded.GetValueOrDefault(ch);
                var skipped = result.ReferencesSkipped.GetValueOrDefault(ch);
                t.AddRow($"References ({ch})", $"[green]{added} added[/]  [grey]{skipped} skipped[/]");
            }
        }
        else
        {
            t.AddRow("References", "[grey]none[/]");
        }
        t.AddRow("Lessons appended", $"[green]{result.LessonsAppended}[/]");

        AnsiConsole.Write(t);
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine("[green]✓[/] Run [bold]pks writing profile show[/] to verify, then [bold]pks writing score[/] some posts.");
        return 0;
    }

    private static string ExpandHome(string path) =>
        path.StartsWith("~/", StringComparison.Ordinal)
            ? System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), path[2..])
            : path;
}
